# Generated by Django 2.1.4 on 2018-12-28 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarksapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folders',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='folders',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='folders',
            name='slug',
            field=models.SlugField(),
        ),
    ]
