# Generated by Django 2.1.4 on 2019-01-02 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarksapp', '0001_initial'),
    ]
    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='Bookmarks',
            new_name='Bookmark',
        ),
        migrations.RenameModel(
            old_name='Folders',
            new_name='Folder',
        ),
    ]
